sudo: required

language: java

services: 
  - docker

before_install:
   - mvn clean install
   - docker build -t eltonmmoreira/wallet -f Dockerfile .

script:
   - docker run -p 8080:8080 eltonmmoreira/wallet 
