sudo: required

# language: java

# jdk: openjdk15

# cache:
#   directories:
#   - $HOME/.m2

# install: true

services: 
  - docker
  
# before_script: 
#   - docker build -t eltonmmoreira/wallet -f Dockerfile .

script:
#    - docker run -p 8080:8080 eltonmmoreira/wallet 
  - docker build -t wallet -f Dockerfile .

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag wallet $DOCKER_USER/wallet:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USER/wallet:$TRAVIS_BUILD_NUMBER
  - docker tag wallet $DOCKER_USER/wallet:latest
  - docker push $DOCKER_USER/wallet:latest
