sudo: required

# language: java

# jdk: openjdk15

# cache:
#   directories:
#   - $HOME/.m2

# install: true
    
services: 
  - docker
  
# before_script: 
#   - docker build -t eltonmmoreira/wallet -f Dockerfile .

script:
#    - docker run -p 8080:8080 eltonmmoreira/wallet 
  - docker build -t demo-wallet -f Dockerfile .
  
after_success:
  - bash <(curl -s https://codecov.io/bash)  
  
before_deploy:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag demo-wallet $DOCKER_USER/demo-wallet:$TRAVIS_BUILD_NUMBER
  - docker tag demo-wallet $DOCKER_USER/demo-wallet:latest
  
deploy:
  provider: script
  script: docker push $DOCKER_USER/demo-wallet:$TRAVIS_BUILD_NUMBER && docker push $DOCKER_USER/demo-wallet:latest
  on:
    branch: master  
