sudo: required

language: java

jdk: openjdk15

cache:
  directories:
  - $HOME/.m2

install: true

# services: 
#   - docker

# install: 
#   - mvn clean install
  
# before_script: 
#   - docker build -t eltonmmoreira/wallet -f Dockerfile .

# script:
#    - docker run -p 8080:8080 eltonmmoreira/wallet 
